---
version: 2.1

orbs:
  twilio: sandbox/twilio@volatile

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:latest

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run: yamllint -d relaxed .

  validate:
    executor: cli
    steps:
      - checkout
      - run: circleci orb validate src/@orb.yml
  sendsms:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0     # toggle this to force success or status for testing
      - twilio/sendsms:
          body: "New alert via SMS"

  publish-dev:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish src/@orb.yml sandbox/twilio@volatile --token $CIRCLE_TOKEN

workflows:
  validate-test-deploy:
    jobs:
      - lint
      - validate:
          requires:
            - lint
      - sendsms:
          requires:
            - validate
      - publish-dev:
          requires:
            - sendsms
